(******************************************************************************)
(*                                                                            *)
(*                       The Moonwalk: Backslide Kinematics                   *)
(*                                                                            *)
(*     Formalizes the biomechanics of the moonwalk (backslide): the           *)
(*     alternating flat-foot/toe-raised cycle, center-of-mass trajectory,     *)
(*     and visual paradox of apparent forward gait with net backward          *)
(*     displacement. Proves illusion conditions from friction constraints.    *)
(*     Extracts to a pose-sequence validator for motion capture training.     *)
(*                                                                            *)
(*     "I never tried to do the moonwalk, it just happened."                  *)
(*     - Michael Jackson, 1988                                                *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: February 2, 2026                                                 *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
